services:
  load_balancer:
    container_name: load_balancer
    build: ./load_balancer
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - event_service
      - user_registration_service

  auth_service:
    build: ./auth_service
    depends_on:
      - caching_service
    deploy:
      replicas: 3
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  event_service:
    build: ./event_service
    depends_on:
      - caching_service
    deploy:
      replicas: 3
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  user_registration_service:
    build: ./user_registration_service
    depends_on:
      - caching_service
    deploy:
      replicas: 3
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  caching_service:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./caching_service/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    restart: always
    ports:
      - "8070:80"

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin

  # mysqld-exporter:
  #   image: prom/mysqld-exporter
  #   container_name: mysqld-exporter
  #   restart: unless-stopped
  #   ports:
  #     - "9104:9104"
  #   environment:
  #     - DATA_SOURCE_NAME=root:root@(${DB_HOST}:${DB_PORT})/